<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.list.tags
 * Tags=page.list.tpl:{LIST_TOP_SORT},{LIST_TOP_WAY},{LIST_TOP_MAXPERPAGE}
 * [END_COT_EXT]
 */
 
/**
 * plugin List Sorters for Cotonti Siena
 * 
 * @package listsorters
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
$cfg['plugin']['listsorters']['fields'] = str_replace(' ', '', $cfg['plugin']['listsorters']['fields']);
$cfg['plugin']['listsorters']['counts'] = str_replace(' ', '', $cfg['plugin']['listsorters']['counts']);
$mainflds = array('title' => $L['Title'], 'key' => $L['Key'], 'date' => $L['Date'], 'author' => $L['Author'], 'owner' => $L['Owner'], 'count' => $L['Hits'], 'filecount' => $L['Downloaded']);
$jumpboxfields = !empty($cfg['plugin']['listsorters']['fields']) ? explode(',', $cfg['plugin']['listsorters']['fields']) : array();
$build_forms_sort = array();
foreach ($cot_extrafields[$db_pages] + $mainflds as $row_k => $row_p)
{
	$hrefs = cot_url('page', array('s' => $row_k) + $list_url_path, '', true);
	if(in_array($row_k, array('title', 'key', 'date', 'author', 'owner', 'count', 'filecount')))
	{
		$titles = $row_p;
	}
	else
	{
		$titles = isset($L['page_'.$row_k.'_title']) ?	$L['page_'.$row_k.'_title'] : $row_p['field_description'];
	}	
	
	if (empty($cfg['plugin']['listsorters']['fields']) || in_array($row_k, $jumpboxfields))
	{
		$build_forms_sort[$hrefs] = $titles;
	}
}
$build_forms_way[cot_url('page', array('w' => 'asc') + $list_url_path, '', true)] = $L['Ascending'];
$build_forms_way[cot_url('page', array('w' => 'desc') + $list_url_path, '', true)] = $L['Descending'];

$jumpboxcount = !empty($cfg['plugin']['listsorters']['counts']) ? explode(',', $cfg['plugin']['listsorters']['counts']) : array(10, 15, 20, 30, 50, 100);
foreach($jumpboxcount as $row_k => $row_p)
{
	$hrefs = cot_url('page', array('perpage' => $row_p) + $list_url_path, '', true);
	$build_forms_count[$hrefs] = $row_p;
}

$t->assign(array(
	"LIST_TOP_SORT" => cot_selectbox(cot_url('page', array('s' => $s) + $list_url_path, '', true), 'jumpboxsort', array_keys($build_forms_sort), array_values($build_forms_sort), false, 'onchange="redirect(this)"'),
	"LIST_TOP_WAY" => cot_selectbox(cot_url('page', array('w' => $w) + $list_url_path, '', true), 'jumpboxway', array_keys($build_forms_way), array_values($build_forms_way), false, 'onchange="redirect(this)"'),
	"LIST_TOP_MAXPERPAGE" => cot_selectbox(cot_url('page', array('perpage' => $perpage) + $list_url_path, '', true), 'jumpboxperpage', array_keys($build_forms_count), array_values($build_forms_count), false, 'onchange="redirect(this)"'),
))


?>
 
