<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.list.query
 * [END_COT_EXT]
 */
 
/**
 * plugin List Sorters for Cotonti Siena
 * 
 * @package listsorters
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

$perpage = cot_import('perpage', 'G', 'INT'); // order way (asc, desc)

if ($perpage > 0)
{
	$_SESSION['userset'][$c]['perpage'] = $perpage;
}

if(isset($_SESSION['userset'][$c]['perpage']))
{
	$perpage = $_SESSION['userset'][$c]['perpage'];
}

if((int)$perpage > 0)
{
	$cfg['page']['maxrowsperpage'] = (int)$perpage;
}
else
{
	$perpage = $cfg['page']['maxrowsperpage'];
}
	
?>
 
