<?php


/**
 * [BEGIN_COT_EXT]
 * Code=listsorters
 * Name=List Sorters
 * Description=List sorters form
 * Version=1.0.0
 * Date=2012-01-19
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * Requires_modules=page
 * [END_COT_EXT]
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * fields=01:string:::Sort order fields, comma sep
 * counts=03:string:::Per page count, comma sep
 * [END_COT_EXT_CONFIG]
 * 
 *  */

/**
 * plugin List Sorters for Cotonti Siena
 * 
 * @package listsorters
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>
